import React from 'react';
import { Sparkles, Clock, Cpu, Zap } from 'lucide-react';

const AIResponseDisplay = ({ response, title = 'AI Analysis' }) => {
  if (!response) return null;

  const formatContent = (content) => {
    // Split content into sections based on numbered items or headers
    const lines = content.split('\n');
    let formattedContent = [];
    let currentSection = null;

    lines.forEach((line, index) => {
      const trimmedLine = line.trim();

      // Check for numbered sections (1., 2., etc.)
      const numberMatch = trimmedLine.match(/^(\d+)\.\s*\*?\*?([^*]+)\*?\*?:?\s*(.*)/);
      // Check for headers with ** or bold text
      const headerMatch = trimmedLine.match(/^\*\*([^*]+)\*\*/);
      // Check for bullet points
      const bulletMatch = trimmedLine.match(/^[-•]\s*(.*)/);

      if (numberMatch) {
        formattedContent.push(
          <div key={index} style={{ marginBottom: '16px' }}>
            <div style={{
              display: 'flex',
              alignItems: 'flex-start',
              gap: '12px',
              marginBottom: '8px'
            }}>
              <span style={{
                background: 'linear-gradient(135deg, #4f46e5, #7c3aed)',
                color: 'white',
                width: '28px',
                height: '28px',
                borderRadius: '8px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontWeight: '700',
                fontSize: '14px',
                flexShrink: 0
              }}>
                {numberMatch[1]}
              </span>
              <div>
                <h4 style={{
                  color: '#a5b4fc',
                  fontWeight: '600',
                  fontSize: '15px',
                  marginBottom: '4px'
                }}>
                  {numberMatch[2].replace(/[*:]/g, '').trim()}
                </h4>
                {numberMatch[3] && (
                  <p style={{ color: '#e4e4e7', fontSize: '14px', lineHeight: '1.7' }}>
                    {numberMatch[3]}
                  </p>
                )}
              </div>
            </div>
          </div>
        );
      } else if (headerMatch && !numberMatch) {
        formattedContent.push(
          <h3 key={index} style={{
            color: '#c4b5fd',
            fontWeight: '600',
            fontSize: '16px',
            marginTop: '20px',
            marginBottom: '12px',
            borderBottom: '1px solid rgba(79, 70, 229, 0.3)',
            paddingBottom: '8px'
          }}>
            {headerMatch[1]}
          </h3>
        );
      } else if (bulletMatch) {
        formattedContent.push(
          <div key={index} style={{
            display: 'flex',
            gap: '10px',
            marginBottom: '8px',
            paddingLeft: '8px'
          }}>
            <span style={{ color: '#4f46e5', fontSize: '8px', marginTop: '8px' }}>●</span>
            <p style={{ color: '#e4e4e7', fontSize: '14px', lineHeight: '1.7' }}>
              {bulletMatch[1]}
            </p>
          </div>
        );
      } else if (trimmedLine) {
        formattedContent.push(
          <p key={index} style={{
            color: '#e4e4e7',
            fontSize: '14px',
            lineHeight: '1.7',
            marginBottom: '8px'
          }}>
            {trimmedLine.replace(/\*\*/g, '')}
          </p>
        );
      }
    });

    return formattedContent;
  };

  return (
    <div className="ai-response">
      <div className="ai-response-header">
        <div className="ai-response-icon">
          <Sparkles size={22} color="white" />
        </div>
        <div>
          <h3 className="ai-response-title">{title}</h3>
          <p style={{ fontSize: '12px', color: '#71717a' }}>Generated by AI</p>
        </div>
      </div>

      <div style={{
        background: 'rgba(0, 0, 0, 0.2)',
        borderRadius: '12px',
        padding: '20px',
        marginBottom: '16px'
      }}>
        {formatContent(response.content)}
      </div>

      <div className="ai-response-meta">
        <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
          <Cpu size={14} />
          <span>Model: {response.model || 'claude-haiku'}</span>
        </div>
        {response.usage && (
          <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
            <Zap size={14} />
            <span>Tokens: {response.usage.total_tokens || 'N/A'}</span>
          </div>
        )}
        <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
          <Clock size={14} />
          <span>{new Date(response.timestamp).toLocaleString()}</span>
        </div>
      </div>
    </div>
  );
};

export default AIResponseDisplay;
